name: Build MapArtsMerger

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build executable
        run: pyinstaller --onefile --windowed --icon=icon.ico MapArtsMerger.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-app
          path: dist/MapArtsMerger.exe

      - name: Release artifact
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MapArtsMerger.exe
          tag_name: latest
          name: Latest Release
          body: "Automated release of the latest version."
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
